openapi: 3.0.0
info:
  title: Movie Quotes API
  description: API documentation of Movie Quotes API
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:4444
    description: local server
  - url: http://producation.app
    description: production server

paths:
  # Users
  /activate-account:
    get:
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Check your email after registration and enter JWT token which you got
      tags:
        - User
      description: Activate user account after registration with JWT token
      responses:
        '200':
          description: Account activated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Account activated successfully!
        '403':
          description: Provided JWT token is invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Account activation failed. JWT token is invalid!
        '404':
          description: User account not found. User is not registered yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User is not registered yet!

  /verify-email:
    get:
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
          description: Enter your email address
      tags:
        - User
      description: Verify email address and get email with JWT token
      responses:
        '200':
          description: Email verified successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Email verification link sent. Check your email.
        '404':
          description: User account with this email address not found. User is not registered yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User with this email is not registered yet.
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  /register-user:
    post:
      tags:
        - User
      description: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: number
            example:
              name: 'john'
              email: 'john@gmail.com'
              password: 'password'
      responses:
        '201':
          description: User registered successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User registered successfully! Account verification link sent.
        '401':
          description: Email Couldn't be sent because mailing service api key is missing or is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Sendgrid api key is missing!
        '409':
          description: User already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User is already registered!
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.

  /register-google-user:
    post:
      tags:
        - User
      description: Register new user after google authentication and get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
            example:
              name: 'john'
              email: 'john@gmail.com'
      responses:
        '200':
          description: JWT token sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                example:
                  message: JWT token
        '422':
          description: Unprocessed Entity
        '500':
          description: Internal Server Error.
