openapi: 3.0.0
info:
  title: NodeJS Project
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:4444
    description: local server
  - url: http://producation.app
    description: production server

paths:
  /activate-account:
    get:
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Check your email after registration and enter JWT token which you got
      tags:
        - User
      description: Activate user account after registration with JWT token
      responses:
        '200':
          description: Account activated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Account activated successfully!
        '403':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Account activation failed. JWT token is invalid!
        '404':
          description: User account not found. User is not registered yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User is not registered yet!
